package rdp

import (
	"crypto/hmac"
	"crypto/md5"
	"encoding/binary"
	"strings"
	"time"
)

// computeNTLMv2 computes the NTLMv2 NT response and session base key.
// password, username, domain should be provided as UTF-8 strings.
// serverChallenge is 8 bytes from the NTLM Challenge message.
// clientChallenge is 8 random bytes generated by the client.
// targetInfo is the AvPairs blob from the Challenge message.
func computeNTLMv2(password, username, domain string,
	serverChallenge, clientChallenge, targetInfo []byte,
) (ntResponse []byte, sessionBaseKey []byte, err error) {
	// NT hash: MD4(UTF-16LE(password))
	ntHash := ntHash(password)

	// NTLMv2 hash: HMAC-MD5(NT_hash, UTF-16LE(upper(user) + domain))
	identity := encodeUTF16LE(strings.ToUpper(username) + domain)
	ntlmv2Hash := hmacMD5(ntHash, identity)

	// Blob (NTChallengeResponse blob part)
	blob := buildNTLMv2Blob(clientChallenge, targetInfo)

	// NTProofStr: HMAC-MD5(NTLMv2_hash, server_challenge + blob)
	ntProofStr := hmacMD5(ntlmv2Hash, append(serverChallenge, blob...))

	// NT response = NTProofStr + blob
	ntResponse = append(ntProofStr, blob...)

	// Session base key = HMAC-MD5(NTLMv2_hash, NTProofStr)
	sessionBaseKey = hmacMD5(ntlmv2Hash, ntProofStr)

	return ntResponse, sessionBaseKey, nil
}

// ntHash computes the NT Hash: MD4(UTF-16LE(password)).
func ntHash(password string) []byte {
	return md4(encodeUTF16LE(password))
}

func buildNTLMv2Blob(clientChallenge, targetInfo []byte) []byte {
	now := time.Now().UTC()
	// Windows FILETIME: 100-nanosecond intervals since Jan 1, 1601
	epoch := time.Date(1601, 1, 1, 0, 0, 0, 0, time.UTC)
	ft := uint64(now.Sub(epoch).Nanoseconds() / 100)

	blob := make([]byte, 0, 28+len(targetInfo))
	blob = append(blob, 0x01, 0x01, 0x00, 0x00) // Signature
	blob = append(blob, 0x00, 0x00, 0x00, 0x00) // Reserved
	blob = binary.LittleEndian.AppendUint64(blob, ft)
	blob = append(blob, clientChallenge...)
	blob = append(blob, 0x00, 0x00, 0x00, 0x00) // Reserved
	blob = append(blob, targetInfo...)
	blob = append(blob, 0x00, 0x00, 0x00, 0x00) // AvPair terminator
	return blob
}

func hmacMD5(key, data []byte) []byte {
	h := hmac.New(md5.New, key)
	h.Write(data)
	return h.Sum(nil)
}

// md4 computes the MD4 hash — required for NT hash.
// Implemented directly to avoid external dependencies.
func md4(data []byte) []byte {
	var x [16]uint32
	var state [4]uint32

	state[0] = 0x67452301
	state[1] = 0xefcdab89
	state[2] = 0x98badcfe
	state[3] = 0x10325476

	msg := pad(data)
	for i := 0; i < len(msg); i += 64 {
		block := msg[i : i+64]
		for j := 0; j < 16; j++ {
			x[j] = binary.LittleEndian.Uint32(block[j*4 : j*4+4])
		}
		a, b, c, d := state[0], state[1], state[2], state[3]

		// Round 1
		for _, s := range []struct{ i, s int }{{0, 3}, {1, 7}, {2, 11}, {3, 19}, {4, 3}, {5, 7}, {6, 11}, {7, 19}, {8, 3}, {9, 7}, {10, 11}, {11, 19}, {12, 3}, {13, 7}, {14, 11}, {15, 19}} {
			f := (b & c) | (^b & d)
			t := a + f + x[s.i]
			a, b, c, d = d, leftRotate(t, s.s), b, c
		}
		// Round 2
		for _, si := range []struct{ i, s int }{{0, 3}, {4, 5}, {8, 9}, {12, 13}, {1, 3}, {5, 5}, {9, 9}, {13, 13}, {2, 3}, {6, 5}, {10, 9}, {14, 13}, {3, 3}, {7, 5}, {11, 9}, {15, 13}} {
			f := (b & c) | (b & d) | (c & d)
			t := a + f + x[si.i] + 0x5a827999
			a, b, c, d = d, leftRotate(t, si.s), b, c
		}
		// Round 3
		for _, si := range []struct{ i, s int }{{0, 3}, {8, 9}, {4, 11}, {12, 15}, {2, 3}, {10, 9}, {6, 11}, {14, 15}, {1, 3}, {9, 9}, {5, 11}, {13, 15}, {3, 3}, {11, 9}, {7, 11}, {15, 15}} {
			f := b ^ c ^ d
			t := a + f + x[si.i] + 0x6ed9eba1
			a, b, c, d = d, leftRotate(t, si.s), b, c
		}

		state[0] += a
		state[1] += b
		state[2] += c
		state[3] += d
	}

	out := make([]byte, 16)
	binary.LittleEndian.PutUint32(out[0:], state[0])
	binary.LittleEndian.PutUint32(out[4:], state[1])
	binary.LittleEndian.PutUint32(out[8:], state[2])
	binary.LittleEndian.PutUint32(out[12:], state[3])
	return out
}

func pad(msg []byte) []byte {
	l := len(msg)
	result := append(msg, 0x80)
	for len(result)%64 != 56 {
		result = append(result, 0)
	}
	result = binary.LittleEndian.AppendUint64(result, uint64(l*8))
	return result
}

func leftRotate(x uint32, s int) uint32 {
	return (x << s) | (x >> (32 - s))
}
